version: '3'
services:
  python3:
    restart: always
    image: python:3.7
    build: .
    container_name: 'python-playground3.7'
    working_dir: '/root/'
    command: 'tail -f /dev/null'
    volumes:
      - ./opt:/root/opt
